### ISSUE TITLE
puppet-quest-guide/en_us/quests/agent_run.md is missing Test 5 description

### ISSUE THREAD

**Issue by arabkin** [puppetlabs/puppet-quest-guide#237]
Hi,

I've used the latest Learning VM (downloaded yesterday) for my puppet learning journey and I've found that it's missing Test 5 description in __puppet-quest-guide/en_us/quests/agent_run.md__

**Comment by greglarkin** [comment]
Hello @arabkin, it has taken us a while to respond to this, and my apologies for that. I am in the midst of preparing an update to the Learning VM with PE 2019 installed.

Can you specify more clearly what the problem is that you have reported? I'm not sure I understand what is missing from the `agent_run` quest.
